/* @generated by: make gen-init-blob-bindings — do not edit manually. */
#ifndef LIBKRUN_INIT_H
#define LIBKRUN_INIT_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

typedef void* KrunInitConfigError;
typedef void* KrunInitGuestFile;
typedef void* KrunInitConfig;
typedef void* KrunInitConfigBuilder;
typedef void* KrunInitError; /* KrunInitVtableError */
typedef void* KrunInitPushStr; /* KrunInitVtablePushStr */

#ifndef KRUN_PRIMITIVES_DEFINED
#define KRUN_PRIMITIVES_DEFINED

typedef void* KrunObject; /* KrunInitConfigError | KrunInitGuestFile | KrunInitConfig | KrunInitConfigBuilder */

typedef uint64_t KrunResult;
#define KRUN_RESULT_SUCCESS 0

/* Caller must ensure data is valid UTF-8 */
typedef struct {
    const char* data;
    size_t len;
} KrunStr;

typedef struct {
    const uint8_t* data;
    size_t len;
} KrunBytes;

#define KRUN_STR(s) ((KrunStr){ .data = (s), .len = (s) ? strlen(s) : 0 })
#if defined(__GNUC__)
#define KRUN_BYTES(arr) ({ \
    _Static_assert( \
        !__builtin_types_compatible_p(typeof(arr), typeof(&(arr)[0])), \
        "KRUN_BYTES() requires an array, not a pointer"); \
    ((KrunBytes){ .data = (const uint8_t*)(arr), .len = sizeof(arr) }); \
})
#else
#define KRUN_BYTES(arr) \
    ((KrunBytes){ .data = (const uint8_t*)(arr), .len = sizeof(arr) })
#endif

/**
 * Stack-allocated temporary handle for passing vtable-based objects.
 * Only valid for the duration of the call — the callee borrows, not owns.
 */
typedef struct {
    uint32_t type_tag;
    uint32_t metadata;
    const void *vtable_ptr;
    const void *user_data;
    uint16_t vtable_size;
} KrunVtableHandle;

#define KRUN_VTABLE_HANDLE(tag, vtable, self_data) \
    ((KrunVtableHandle){ .type_tag = (tag), .metadata = 0, \
      .vtable_ptr = &(vtable), .user_data = (self_data), \
      .vtable_size = sizeof(vtable) })

/**
 * Opaque 16-byte handle entry in an object array.
 * Do not access fields directly — pass &entry to typed methods.
 * Do NOT pass individual entries to destroy.
 */
typedef struct {
    uint32_t _tag;
    uint32_t _meta;
    const void* _ptr;
} KrunObjectArrayEntry;

/**
 * Contiguous array of borrowed handles.
 * Returned by methods that produce slices of handles.
 * Individual elements must NOT be passed to destroy —
 * call free_object_array() to free the entire array.
 */
typedef struct {
    const KrunObjectArrayEntry* items;
    size_t len;
} KrunObjectArray;

#define KRUN_OBJECT_ARRAY_GET(arr, i) \
    (assert((size_t)(i) < (arr).len), (KrunObject)(void*)&(arr).items[(i)])

#endif /* KRUN_PRIMITIVES_DEFINED */

/* Free an owned string returned by the library */
void krun_init_str_free(KrunStr s);

/* Free an object array returned by the library */
void krun_init_free_object_array(KrunObjectArray a);


/* ConfigError ------------------------------------------------------- */

#define KRUN_INIT_ERROR_CONFIG_INVALID_JSON ((uint64_t)33554435 << 32 | 1)

/* GuestFile --------------------------------------------------------- */

/** Path on the guest root filesystem (e.g. `"/init.krun"`). */
KrunStr krun_init_guest_file_path(KrunInitGuestFile handle);
/** File contents. */
KrunBytes krun_init_guest_file_data(KrunInitGuestFile handle);
/** Permission mode bits (e.g. `0o755`). */
uint32_t krun_init_guest_file_mode(KrunInitGuestFile handle);
/** Whether this file is one-shot (removed after first lookup). */
bool krun_init_guest_file_one_shot(KrunInitGuestFile handle);
void krun_init_guest_file_destroy(KrunInitGuestFile handle);

/* Config ------------------------------------------------------------ */

/** Start building a new init configuration. */
KrunInitConfigBuilder krun_init_config_builder();
/**
 * Construct from an OCI runtime-spec config.json string.
 *
 * The JSON is expected to use the OCI runtime-spec layout:
 * `{"process": {"args": [...], "env": [...], "cwd": "..."}, "mounts": [...]}`.
 *
 * # Errors
 *
 * Returns `Err` if the JSON is syntactically invalid or contains
 * unexpected types.
 */
KrunInitConfig krun_init_config_from_oci_config_json(KrunStr json, KrunInitError* err_out);
/**
 * Returns the kernel cmdline argument needed to boot with this init
 * (e.g. `"init=/init.krun"`). Pass this to `krun_set_kernel_args`.
 */
KrunStr krun_init_config_kernel_init_arg(KrunInitConfig handle);
/**
 * Returns the guest files that need to be injected into the guest
 * root filesystem.
 */
KrunObjectArray krun_init_config_guest_files(KrunInitConfig handle);
void krun_init_config_destroy(KrunInitConfig handle);

/* ConfigBuilder ----------------------------------------------------- */

/** Set the full argv: `args[0]` is the executable, `args[1..]` are arguments. */
void krun_init_config_builder_args(KrunInitConfigBuilder* handle, const KrunStr* argv, size_t argv_len);
/** Set environment variables. Each entry should be `"KEY=value"`. */
void krun_init_config_builder_env(KrunInitConfigBuilder* handle, const KrunStr* vars, size_t vars_len);
/** Set the guest working directory. */
void krun_init_config_builder_workdir(KrunInitConfigBuilder* handle, KrunStr dir);
/** Add a mount specification. */
void krun_init_config_builder_mount(KrunInitConfigBuilder* handle, KrunStr destination, KrunStr fs_type, KrunStr source);
/** Set resource limits. Each entry should be `"id=cur:max"` (e.g. `"7=0:0"`). */
void krun_init_config_builder_rlimits(KrunInitConfigBuilder* handle, const KrunStr* limits, size_t limits_len);
/**
 * Consume the builder, serialize the config, and return the
 * finished [`Config`].
 */
KrunInitConfig krun_init_config_builder_build(KrunInitConfigBuilder* handle);
void krun_init_config_builder_destroy(KrunInitConfigBuilder handle);

/* KrunInitPushStrVtable --------------------------------------------- */

#define KRUN_INIT_PUSH_STR_TYPE_TAG 33554433

typedef struct {
    void (*drop)(void* self_data);
    bool (*push)(void* self_data, KrunStr s);
} KrunInitPushStrVtable;

/* PushStr (dispatch) ------------------------------------------------ */

bool krun_init_push_str_push(KrunInitPushStr handle, KrunStr s);
void krun_init_push_str_destroy(KrunInitPushStr handle);

/* KrunInitErrorVtable ----------------------------------------------- */

#define KRUN_INIT_ERROR_TYPE_TAG 33554434

typedef struct {
    void (*drop)(void* self_data);
    uint32_t (*code)(void* self_data);
    void (*message)(void* self_data, KrunInitPushStr writer);
    uint64_t (*result)(void* self_data);
} KrunInitErrorVtable;

/* Error (dispatch) -------------------------------------------------- */

uint32_t krun_init_error_code(KrunInitError handle);
void krun_init_error_message(KrunInitError handle, KrunInitPushStr writer);
uint64_t krun_init_error_result(KrunInitError handle);
void krun_init_error_destroy(KrunInitError handle);
KrunStr krun_init_result_name(KrunResult r);
const char* krun_init_result_name_cstr(KrunResult r);

#endif /* LIBKRUN_INIT_H */
