/* @generated by: make gen-init-blob-bindings — do not edit manually. */
#ifndef LIBKRUN_INIT_H
#define LIBKRUN_INIT_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

typedef void* KrunInitConfigError;
typedef void* KrunInitApplyError;
typedef void* KrunInitConfig;
typedef void* KrunInitBuilder;
typedef void* KrunInitError; /* KrunInitConfigError | KrunInitApplyError | KrunInitVtableError */
typedef void* KrunInitPushStr; /* KrunInitVtablePushStr */

#ifndef KRUN_PRIMITIVES_DEFINED
#define KRUN_PRIMITIVES_DEFINED

typedef void* KrunObject; /* KrunInitConfigError | KrunInitApplyError | KrunInitConfig | KrunInitBuilder */

typedef uint64_t KrunResult;
#define KRUN_RESULT_SUCCESS 0

/* Caller must ensure data is valid UTF-8 */
typedef struct {
    const char* data;
    size_t len;
} KrunStr;

#define KRUN_STR(s) ((KrunStr){ .data = (s), .len = (s) ? strlen(s) : 0 })
/**
 * Stack-allocated temporary handle for passing vtable-based objects.
 * Only valid for the duration of the call — the callee borrows, not owns.
 */
typedef struct {
    uint32_t type_tag;
    uint32_t metadata;
    const void *vtable_ptr;
    const void *user_data;
    uint16_t vtable_size;
} KrunVtableHandle;

#define KRUN_VTABLE_HANDLE(tag, vtable, self_data) \
    ((KrunVtableHandle){ .type_tag = (tag), .metadata = 0, \
      .vtable_ptr = &(vtable), .user_data = (self_data), \
      .vtable_size = sizeof(vtable) })

/**
 * Opaque 16-byte handle entry in an object array.
 * Do not access fields directly — pass &entry to typed methods.
 * Do NOT pass individual entries to destroy.
 */
typedef struct {
    uint32_t _tag;
    uint32_t _meta;
    const void* _ptr;
} KrunObjectArrayEntry;

/**
 * Contiguous array of borrowed handles.
 * Returned by methods that produce slices of handles.
 * Individual elements must NOT be passed to destroy —
 * call free_object_array() to free the entire array.
 */
typedef struct {
    const KrunObjectArrayEntry* items;
    size_t len;
} KrunObjectArray;

#define KRUN_OBJECT_ARRAY_GET(arr, i) \
    (assert((size_t)(i) < (arr).len), (KrunObject)(void*)&(arr).items[(i)])

#endif /* KRUN_PRIMITIVES_DEFINED */

/* Free an owned string returned by the library */
void krun_init_str_free(KrunStr s);

/* Free an object array returned by the library */
void krun_init_free_object_array(KrunObjectArray a);


/* ConfigError ------------------------------------------------------- */

#define KRUN_INIT_ERROR_CONFIG_INVALID_JSON ((uint64_t)33554435 << 32 | 1)

/* ApplyError -------------------------------------------------------- */

#define KRUN_INIT_ERROR_APPLY_SYMBOL_NOT_FOUND ((uint64_t)33554438 << 32 | 1)
#define KRUN_INIT_ERROR_APPLY_OVERLAY_FILE ((uint64_t)33554438 << 32 | 2)
#define KRUN_INIT_ERROR_APPLY_KERNEL_CMDLINE ((uint64_t)33554438 << 32 | 3)

/* Config ------------------------------------------------------------ */

/** Start building a new init configuration. */
KrunInitBuilder krun_init_config_builder();
/**
 * Returns the kernel cmdline argument needed to boot with this init
 * (e.g. `"init=/init.krun"`). Pass this to `krun_set_kernel_args`.
 */
KrunStr krun_init_config_kernel_init_arg(KrunInitConfig handle);
/**
 * Apply this init configuration to a libkrun VM context.
 *
 * Adds the init binary and associated configuration file(s) as
 * overlay files on the specified virtiofs device, and appends
 * the appropriate kernel command line argument to specify the
 * init binary.
 *
 * `lib_handle` is the result of `dlopen("libkrun.so")`. Pass NULL to
 * search the global symbol namespace (requires libkrun was linked or
 * opened with `RTLD_GLOBAL`).
 *
 * # Safety
 *
 * - If `lib_handle` is non-null it must be a valid handle returned by
 *   `dlopen` (or equivalent) that remains open for the duration of
 *   this call.
 * - The caller must keep this `Config` alive for the entire lifetime
 *   of the VM. `apply` passes data pointers to libkrun that remain
 *   borrowed until the VM exits.
 */
KrunResult krun_init_config_apply(KrunInitConfig handle, void* lib_handle, uint32_t ctx_id, KrunStr fs_tag, KrunInitError* err_out);
void krun_init_config_destroy(KrunInitConfig handle);

/* Builder ----------------------------------------------------------- */

/**
 * Parse an OCI runtime-spec config.json string into a builder.
 *
 * Unknown fields are silently ignored. The caller can further
 * modify the builder (e.g. add rlimits, mounts) before calling
 * [`build()`](Self::build).
 */
KrunInitBuilder krun_init_builder_from_oci_json(KrunStr json, KrunInitError* err_out);
/** Append a single argument to argv. */
void krun_init_builder_arg(KrunInitBuilder* handle, KrunStr arg);
/** Append multiple arguments to argv. */
void krun_init_builder_args(KrunInitBuilder* handle, const KrunStr* argv, size_t argv_len);
/** Append a single environment variable (`"KEY=value"`). */
void krun_init_builder_env_var(KrunInitBuilder* handle, KrunStr var);
/** Append multiple environment variables. */
void krun_init_builder_env(KrunInitBuilder* handle, const KrunStr* vars, size_t vars_len);
/** Set the guest working directory. */
void krun_init_builder_workdir(KrunInitBuilder* handle, KrunStr dir);
/** Add a mount specification. */
void krun_init_builder_mount(KrunInitBuilder* handle, KrunStr destination, KrunStr fs_type, KrunStr source);
/** Append a single resource limit (`"id=cur:max"`, e.g. `"7=0:0"`). */
void krun_init_builder_rlimit(KrunInitBuilder* handle, KrunStr limit);
/** Append multiple resource limits. */
void krun_init_builder_rlimits(KrunInitBuilder* handle, const KrunStr* limits, size_t limits_len);
/**
 * Consume the builder, serialize the config, and return the
 * finished [`Config`].
 */
KrunInitConfig krun_init_builder_build(KrunInitBuilder* handle);
void krun_init_builder_destroy(KrunInitBuilder handle);

/* KrunInitPushStrVtable --------------------------------------------- */

#define KRUN_INIT_PUSH_STR_TYPE_TAG 33554433

typedef struct {
    void (*drop)(void* self_data);
    bool (*push)(void* self_data, KrunStr s);
} KrunInitPushStrVtable;

/* PushStr (dispatch) ------------------------------------------------ */

bool krun_init_push_str_push(KrunInitPushStr handle, KrunStr s);
void krun_init_push_str_destroy(KrunInitPushStr handle);

/* KrunInitErrorVtable ----------------------------------------------- */

#define KRUN_INIT_ERROR_TYPE_TAG 33554434

typedef struct {
    void (*drop)(void* self_data);
    uint32_t (*code)(void* self_data);
    void (*message)(void* self_data, KrunInitPushStr writer);
    uint64_t (*result)(void* self_data);
} KrunInitErrorVtable;

/* Error (dispatch) -------------------------------------------------- */

uint32_t krun_init_error_code(KrunInitError handle);
void krun_init_error_message(KrunInitError handle, KrunInitPushStr writer);
uint64_t krun_init_error_result(KrunInitError handle);
void krun_init_error_destroy(KrunInitError handle);
uint32_t krun_init_config_error_code(KrunInitConfigError handle);
void krun_init_config_error_message(KrunInitConfigError handle, KrunInitPushStr writer);
uint32_t krun_init_apply_error_code(KrunInitApplyError handle);
void krun_init_apply_error_message(KrunInitApplyError handle, KrunInitPushStr writer);
KrunStr krun_init_result_name(KrunResult r);
const char* krun_init_result_name_cstr(KrunResult r);

#endif /* LIBKRUN_INIT_H */
