#ifndef LIBKRUN_H
#define LIBKRUN_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

typedef void* KrunMmioDeviceManager;
typedef void* KrunFsDevice;
typedef void* KrunConsoleDevice;
typedef void* KrunConsoleBuilder;
typedef void* KrunBalloonDevice;
typedef void* KrunRngDevice;
typedef void* KrunInit;
typedef void* KrunInitBuilder;
typedef void* KrunVmmBuilder;
typedef void* KrunVmm;

/* Caller must ensure data is valid UTF-8 */
typedef struct {
    const char* data;
    uintptr_t len;
} KrunStr;

/* Caller must ensure data is a valid UTF-8 path */
typedef KrunStr KrunPath;

typedef struct {
    const uint8_t* data;
    uintptr_t len;
} KrunBytes;

#define KRUN_STR(s) ((KrunStr){ .data = (s), .len = strlen(s) })
#if defined(__GNUC__)
#define KRUN_BYTES(arr) ({ \
    _Static_assert( \
        !__builtin_types_compatible_p(typeof(arr), typeof(&(arr)[0])), \
        "KRUN_BYTES() requires an array, not a pointer"); \
    ((KrunBytes){ .data = (const uint8_t*)(arr), .len = sizeof(arr) }); \
})
#else
#define KRUN_BYTES(arr) \
    ((KrunBytes){ .data = (const uint8_t*)(arr), .len = sizeof(arr) })
#endif
/* Header auto-generated by ffier */

/* Error ------------------------------------------------------------- */

typedef struct {
    uint64_t code;
    char* _msg; /* private */
} KrunError;

#define KRUN_ERROR_INVALID_PARAM 100
#define KRUN_ERROR_DUPLICATE_DEVICE 101
#define KRUN_ERROR_DEVICE_LIMIT_EXCEEDED 102
#define KRUN_ERROR_MISSING_CONFIG 103
#define KRUN_ERROR_CONFLICTING_CONFIG 104
#define KRUN_ERROR_OUT_OF_RANGE 105
#define KRUN_ERROR_FILE_NOT_FOUND 200
#define KRUN_ERROR_PERMISSION_DENIED 201
#define KRUN_ERROR_RESOURCE_ALLOC 202
#define KRUN_ERROR_BAD_FD 203
#define KRUN_ERROR_BACKEND_UNAVAILABLE 300
#define KRUN_ERROR_FEATURE_DISABLED 301
#define KRUN_ERROR_DISK_FORMAT_ERROR 302
#define KRUN_ERROR_ALREADY_STARTED 400
#define KRUN_ERROR_VALIDATION_FAILED 401
#define KRUN_ERROR_HYPERVISOR_ERROR 402
#define KRUN_ERROR_BOOT_ERROR 403
#define KRUN_ERROR_INTERNAL 900

const char* krun_error_message(const KrunError* err);
void krun_error_free(KrunError* err);

/* MmioDeviceManager ------------------------------------------------- */

typedef void* KrunAttachDevice; /* KrunFsDevice | KrunConsoleDevice | KrunBalloonDevice | KrunRngDevice */
KrunMmioDeviceManager krun_mmio_device_manager_new(void);
void krun_mmio_device_manager_add(KrunMmioDeviceManager handle, KrunAttachDevice device);
void krun_mmio_device_manager_destroy(KrunMmioDeviceManager handle);

/* FsDevice ---------------------------------------------------------- */

KrunError krun_fs_device_new(KrunStr tag, KrunStr host_path, KrunFsDevice* result);
void krun_fs_device_set_dax_window_size(KrunFsDevice handle, uint64_t bytes);
void krun_fs_device_destroy(KrunFsDevice handle);

/* ConsoleDevice ----------------------------------------------------- */

KrunConsoleBuilder krun_console_device_builder(void);
void krun_console_device_destroy(KrunConsoleDevice handle);

/* ConsoleBuilder ---------------------------------------------------- */

KrunError krun_console_builder_add_tty_port(KrunConsoleBuilder handle, KrunStr name, int tty_fd, uint32_t* result);
KrunError krun_console_builder_set_kernel_console(KrunConsoleBuilder handle, uint32_t port_index);
KrunError krun_console_builder_build(KrunConsoleBuilder handle, KrunConsoleDevice* result);
void krun_console_builder_destroy(KrunConsoleBuilder handle);

/* BalloonDevice ----------------------------------------------------- */

KrunError krun_balloon_device_new(KrunBalloonDevice* result);
void krun_balloon_device_destroy(KrunBalloonDevice handle);

/* RngDevice --------------------------------------------------------- */

KrunError krun_rng_device_new(KrunRngDevice* result);
void krun_rng_device_destroy(KrunRngDevice handle);

/* Init -------------------------------------------------------------- */

KrunInitBuilder krun_init_builder(KrunFsDevice _rootfs, KrunConsoleBuilder console);
void krun_init_destroy(KrunInit handle);

/* InitBuilder ------------------------------------------------------- */

/**
 * Auto-detect console setup.
 *
 * Tries /dev/tty (the controlling terminal) first. If available, creates
 * a single TTY port for payload I/O. Otherwise falls back to separate
 * krun-payload-stdin/stdout/stderr redirect ports on the stdio fds.
 *
 * @return KrunError with code 0 on success, error code on failure.
 */
KrunError krun_init_builder_console_auto(KrunInitBuilder* handle);
KrunError krun_init_builder_console_tty(KrunInitBuilder* handle, int tty_fd);
KrunError krun_init_builder_console_redirects(KrunInitBuilder* handle, int32_t stdin_fd, int32_t stdout_fd, int32_t stderr_fd);
KrunError krun_init_builder_exec(KrunInitBuilder* handle, KrunStr exec_path, const KrunStr* args, uintptr_t args_len);
KrunError krun_init_builder_env(KrunInitBuilder* handle, const KrunStr* env, uintptr_t env_len);
KrunError krun_init_builder_workdir(KrunInitBuilder* handle, KrunStr path);
KrunError krun_init_builder_build(KrunInitBuilder handle, KrunInit* result);
void krun_init_builder_destroy(KrunInitBuilder handle);

/* VmmBuilder -------------------------------------------------------- */

typedef void* KrunPayload; /* KrunInit */
KrunVmmBuilder krun_vmm_builder_new(void);
KrunError krun_vmm_builder_vcpus(KrunVmmBuilder* handle, uint8_t count);
KrunError krun_vmm_builder_ram_mib(KrunVmmBuilder* handle, uint32_t mib);
void krun_vmm_builder_payload(KrunVmmBuilder* handle, KrunPayload payload);
void krun_vmm_builder_devices(KrunVmmBuilder* handle, KrunMmioDeviceManager devices);
KrunError krun_vmm_builder_build(KrunVmmBuilder handle, KrunVmm* result);
void krun_vmm_builder_destroy(KrunVmmBuilder handle);

/* Vmm --------------------------------------------------------------- */

void krun_vmm_run(KrunVmm handle);
void krun_vmm_destroy(KrunVmm handle);

/* Log --------------------------------------------------------------- */

#define KRUN_LOG_TARGET_DEFAULT (-1)
#define KRUN_LOG_STYLE_AUTO     0
#define KRUN_LOG_STYLE_ALWAYS   1
#define KRUN_LOG_STYLE_NEVER    2
#define KRUN_LOG_LEVEL_OFF      0
#define KRUN_LOG_LEVEL_ERROR    1
#define KRUN_LOG_LEVEL_WARN     2
#define KRUN_LOG_LEVEL_INFO     3
#define KRUN_LOG_LEVEL_DEBUG    4
#define KRUN_LOG_LEVEL_TRACE    5

KrunError krun_init_log(int target_fd, uint32_t level, uint32_t style);

#endif /* LIBKRUN_H */
