// @generated by: cargo run --bin gen-libkrun-rust-client
// Auto-generated. Regenerate with:
//   cargo run -p libkrun-cdylib --bin gen-libkrun-rust-client > src/libkrun-via-cdylib/src/generated.rs

use std::os::unix::io::{AsRawFd, BorrowedFd, RawFd};

/// Marker trait for types exported as opaque C handles.
pub trait FfiHandle {
    const C_HANDLE_NAME: &'static str;
    const TYPE_TAG: u32;
    /// # Safety
    /// The caller must ensure the handle is not used after the object is dropped.
    unsafe fn as_handle(&self) -> *mut core::ffi::c_void;
    fn __from_raw(handle: *mut core::ffi::c_void) -> Self;
}

/// Maps Rust types to C-compatible representations.
pub trait FfiType {
    type CRepr;
    const C_TYPE_NAME: &'static str;
    const IS_HANDLE: bool = false;
    fn into_c(self) -> Self::CRepr;
    /// # Safety
    /// The C representation must be valid for this type.
    unsafe fn from_c(repr: Self::CRepr) -> Self;
}

macro_rules! impl_ffi_identity {
    ($($t:ty => $n:expr),* $(,)?) => { $(
        impl FfiType for $t {
            type CRepr = $t; const C_TYPE_NAME: &'static str = $n; const IS_HANDLE: bool = false;
            fn into_c(self) -> Self { self } unsafe fn from_c(r: Self) -> Self { r }
        }
    )* };
}
impl_ffi_identity! {
    i8 => "int8_t", i16 => "int16_t", i32 => "int32_t", i64 => "int64_t",
    u8 => "uint8_t", u16 => "uint16_t", u32 => "uint32_t", u64 => "uint64_t",
    isize => "ssize_t", usize => "size_t", bool => "bool",
}

impl FfiType for &str {
    type CRepr = ffier::FfierBytes;
    const C_TYPE_NAME: &'static str = "FfierStr";
    const IS_HANDLE: bool = false;
    fn into_c(self) -> ffier::FfierBytes {
        unsafe { ffier::FfierBytes::from_str(self) }
    }
    unsafe fn from_c(repr: ffier::FfierBytes) -> Self {
        unsafe {
            let b = core::slice::from_raw_parts(repr.data, repr.len);
            core::str::from_utf8_unchecked(b)
        }
    }
}

impl FfiType for Option<&str> {
    type CRepr = ffier::FfierBytes;
    const C_TYPE_NAME: &'static str = "FfierStr";
    const IS_HANDLE: bool = false;
    fn into_c(self) -> ffier::FfierBytes {
        match self {
            Some(s) => unsafe { ffier::FfierBytes::from_str(s) },
            None => ffier::FfierBytes::EMPTY,
        }
    }
    unsafe fn from_c(repr: ffier::FfierBytes) -> Self {
        if repr.data.is_null() {
            None
        } else {
            unsafe {
                Some(core::str::from_utf8_unchecked(core::slice::from_raw_parts(
                    repr.data, repr.len,
                )))
            }
        }
    }
}

impl FfiType for Box<str> {
    type CRepr = ffier::FfierBytes;
    const C_TYPE_NAME: &'static str = "FfierStr";
    const IS_HANDLE: bool = false;
    fn into_c(self) -> ffier::FfierBytes {
        let leaked: &mut str = Box::leak(self);
        ffier::FfierBytes {
            data: leaked.as_mut_ptr() as *const u8,
            len: leaked.len(),
        }
    }
    unsafe fn from_c(repr: ffier::FfierBytes) -> Self {
        unsafe {
            let slice = core::slice::from_raw_parts_mut(repr.data as *mut u8, repr.len);
            Box::from_raw(core::str::from_utf8_unchecked_mut(slice))
        }
    }
}

impl FfiType for &[u8] {
    type CRepr = ffier::FfierBytes;
    const C_TYPE_NAME: &'static str = "FfierBytes";
    const IS_HANDLE: bool = false;
    fn into_c(self) -> ffier::FfierBytes {
        unsafe { ffier::FfierBytes::from_bytes(self) }
    }
    unsafe fn from_c(repr: ffier::FfierBytes) -> Self {
        unsafe {
            if repr.data.is_null() {
                &[]
            } else {
                core::slice::from_raw_parts(repr.data, repr.len)
            }
        }
    }
}

impl<'fd> FfiType for BorrowedFd<'fd> {
    type CRepr = RawFd;
    const C_TYPE_NAME: &'static str = "int";
    const IS_HANDLE: bool = false;
    fn into_c(self) -> RawFd {
        self.as_raw_fd() as RawFd
    }
    unsafe fn from_c(fd: RawFd) -> Self {
        unsafe { BorrowedFd::borrow_raw(fd as _) }
    }
}

impl<'fd> FfiType for Option<BorrowedFd<'fd>> {
    type CRepr = RawFd;
    const C_TYPE_NAME: &'static str = "int";
    const IS_HANDLE: bool = false;
    fn into_c(self) -> RawFd {
        match self {
            Some(fd) => fd.as_raw_fd() as RawFd,
            None => -1,
        }
    }
    unsafe fn from_c(fd: RawFd) -> Self {
        if fd < 0 {
            None
        } else {
            Some(unsafe { BorrowedFd::borrow_raw(fd as _) })
        }
    }
}

impl<T: FfiHandle + 'static> FfiType for &T {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = T::C_HANDLE_NAME;
    const IS_HANDLE: bool = true;
    fn into_c(self) -> *mut core::ffi::c_void {
        unsafe { self.as_handle() }
    }
    unsafe fn from_c(_: *mut core::ffi::c_void) -> Self {
        unimplemented!("client-side &T from_c")
    }
}
impl<T: FfiHandle + 'static> FfiType for &mut T {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = T::C_HANDLE_NAME;
    const IS_HANDLE: bool = true;
    fn into_c(self) -> *mut core::ffi::c_void {
        unsafe { self.as_handle() }
    }
    unsafe fn from_c(_: *mut core::ffi::c_void) -> Self {
        unimplemented!("client-side &mut T from_c")
    }
}

/// Borrowed slice of handles returned from FFI methods.
/// Elements are borrowed — do NOT destroy them individually.
/// Derefs to `&[T]`, so indexing, iteration, `len()`, etc. all work.
/// Dropping this type frees the backing array.
pub struct ForeignSlice<T> {
    raw: ffier::FfierObjectArray,
    elements: Box<[core::mem::ManuallyDrop<T>]>,
}

impl<T: FfiHandle> ForeignSlice<T> {
    fn from_raw(raw: ffier::FfierObjectArray) -> Self {
        let elements: Box<[core::mem::ManuallyDrop<T>]> = (0..raw.len)
            .map(|i| {
                core::mem::ManuallyDrop::new(T::__from_raw(unsafe {
                    ffier::ffier_object_array_get(raw, i)
                }))
            })
            .collect();
        Self { raw, elements }
    }
}

impl<T> core::ops::Deref for ForeignSlice<T> {
    type Target = [T];
    fn deref(&self) -> &[T] {
        // SAFETY: ManuallyDrop<T> is #[repr(transparent)] over T.
        unsafe { core::mem::transmute::<&[core::mem::ManuallyDrop<T>], &[T]>(&self.elements) }
    }
}

impl<T> Drop for ForeignSlice<T> {
    fn drop(&mut self) {
        unsafe { ffier::ffier_object_array_free(self.raw) };
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum LogLevel {
    Off = 0,
    Error = 1,
    Warn = 2,
    Info = 3,
    Debug = 4,
    Trace = 5,
}

impl FfiType for LogLevel {
    type CRepr = u32;
    const C_TYPE_NAME: &'static str = "LogLevel";
    fn into_c(self) -> u32 {
        self as u32
    }
    unsafe fn from_c(repr: u32) -> Self {
        match repr {
            0 => Self::Off,
            1 => Self::Error,
            2 => Self::Warn,
            3 => Self::Info,
            4 => Self::Debug,
            5 => Self::Trace,
            unknown => panic!("invalid LogLevel discriminant: {}", unknown),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum LogStyle {
    Auto = 0,
    Always = 1,
    Never = 2,
}

impl FfiType for LogStyle {
    type CRepr = u32;
    const C_TYPE_NAME: &'static str = "LogStyle";
    fn into_c(self) -> u32 {
        self as u32
    }
    unsafe fn from_c(repr: u32) -> Self {
        match repr {
            0 => Self::Auto,
            1 => Self::Always,
            2 => Self::Never,
            unknown => panic!("invalid LogStyle discriminant: {}", unknown),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum LogTarget {
    Default = 0,
    Stdout = 1,
    Stderr = 2,
}

impl FfiType for LogTarget {
    type CRepr = u32;
    const C_TYPE_NAME: &'static str = "LogTarget";
    fn into_c(self) -> u32 {
        self as u32
    }
    unsafe fn from_c(repr: u32) -> Self {
        match repr {
            0 => Self::Default,
            1 => Self::Stdout,
            2 => Self::Stderr,
            unknown => panic!("invalid LogTarget discriminant: {}", unknown),
        }
    }
}

unsafe extern "C" {
    fn krun_error_payload(
        handle: *const core::ffi::c_void,
        out_buf: *mut core::ffi::c_void,
        buf_size: usize,
    );
}

pub struct ErrorErrorHandle(*mut core::ffi::c_void);
impl ErrorErrorHandle {
    fn handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl Drop for ErrorErrorHandle {
    fn drop(&mut self) {
        if !self.0.is_null() {
            unsafe { krun_error_destroy(self.0) }
        }
    }
}
impl std::fmt::Debug for ErrorErrorHandle {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "ErrorHandle({:?})", self.0)
    }
}

#[derive(Debug)]
pub enum Error {
    InvalidParam(ErrorErrorHandle),
    DuplicateDevice(ErrorErrorHandle),
    DeviceLimitExceeded(ErrorErrorHandle),
    MissingConfig(ErrorErrorHandle),
    ConflictingConfig(ErrorErrorHandle),
    OutOfRange(ErrorErrorHandle),
    FileNotFound(ErrorErrorHandle),
    PermissionDenied(ErrorErrorHandle),
    ResourceAlloc(ErrorErrorHandle),
    BadFd(ErrorErrorHandle),
    BackendUnavailable(ErrorErrorHandle),
    FeatureDisabled(ErrorErrorHandle),
    DiskFormatError(ErrorErrorHandle),
    AlreadyStarted(ErrorErrorHandle),
    ValidationFailed(ErrorErrorHandle),
    HypervisorError(ErrorErrorHandle),
    BootError(ErrorErrorHandle),
    Internal(ErrorErrorHandle),
}

impl Error {
    pub fn from_ffi(r: ffier::FfierResult, err_handle: *mut core::ffi::c_void) -> Self {
        let code = ffier::ffier_result_code(r);
        let handle = ErrorErrorHandle(err_handle);
        match code {
            100u32 => Self::InvalidParam(handle),
            101u32 => Self::DuplicateDevice(handle),
            102u32 => Self::DeviceLimitExceeded(handle),
            103u32 => Self::MissingConfig(handle),
            104u32 => Self::ConflictingConfig(handle),
            105u32 => Self::OutOfRange(handle),
            200u32 => Self::FileNotFound(handle),
            201u32 => Self::PermissionDenied(handle),
            202u32 => Self::ResourceAlloc(handle),
            203u32 => Self::BadFd(handle),
            300u32 => Self::BackendUnavailable(handle),
            301u32 => Self::FeatureDisabled(handle),
            302u32 => Self::DiskFormatError(handle),
            400u32 => Self::AlreadyStarted(handle),
            401u32 => Self::ValidationFailed(handle),
            402u32 => Self::HypervisorError(handle),
            403u32 => Self::BootError(handle),
            900u32 => Self::Internal(handle),
            other => panic!("unknown {} error code {}", "Error", other),
        }
    }
    fn handle_ptr(&self) -> *mut core::ffi::c_void {
        match self {
            Self::InvalidParam(h) => h.handle(),
            Self::DuplicateDevice(h) => h.handle(),
            Self::DeviceLimitExceeded(h) => h.handle(),
            Self::MissingConfig(h) => h.handle(),
            Self::ConflictingConfig(h) => h.handle(),
            Self::OutOfRange(h) => h.handle(),
            Self::FileNotFound(h) => h.handle(),
            Self::PermissionDenied(h) => h.handle(),
            Self::ResourceAlloc(h) => h.handle(),
            Self::BadFd(h) => h.handle(),
            Self::BackendUnavailable(h) => h.handle(),
            Self::FeatureDisabled(h) => h.handle(),
            Self::DiskFormatError(h) => h.handle(),
            Self::AlreadyStarted(h) => h.handle(),
            Self::ValidationFailed(h) => h.handle(),
            Self::HypervisorError(h) => h.handle(),
            Self::BootError(h) => h.handle(),
            Self::Internal(h) => h.handle(),
        }
    }
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        struct FmtWriter(*mut core::ffi::c_void);
        impl PushStr for FmtWriter {
            fn push(&mut self, s: &str) -> bool {
                unsafe {
                    (&mut *(self.0 as *mut std::fmt::Formatter<'_>))
                        .write_str(s)
                        .is_ok()
                }
            }
        }
        let mut __writer = FmtWriter(f as *mut std::fmt::Formatter<'_> as *mut core::ffi::c_void);
        let __vtable: &'static PushStrVtable = FmtWriter::__ffier_vtable();
        let mut __temp = ffier::FfierHandle {
            type_tag: 16777228u32,
            metadata: 0,
            value: ffier::VtableHandle {
                vtable_ptr: __vtable as *const PushStrVtable as *const core::ffi::c_void,
                user_data: &mut __writer as *mut FmtWriter as *const core::ffi::c_void,
                vtable_size: core::mem::size_of::<PushStrVtable>() as u16,
            },
        };
        let __writer_handle =
            &mut __temp as *mut ffier::FfierHandle<ffier::VtableHandle> as *mut core::ffi::c_void;
        unsafe { krun_error_message(self.handle_ptr(), __writer_handle) };
        Ok(())
    }
}

impl std::error::Error for Error {}

unsafe extern "C" {
    pub fn krun_mmio_device_manager_destroy(handle: *mut core::ffi::c_void);
    pub fn krun_mmio_device_manager_new() -> <MmioDeviceManager<'static> as FfiType>::CRepr;
    pub fn krun_mmio_device_manager_add(
        handle: *mut core::ffi::c_void,
        device: *mut core::ffi::c_void,
    );
}

pub struct MmioDeviceManager<'a>(*mut core::ffi::c_void, std::marker::PhantomData<&'a ()>);

impl<'a> MmioDeviceManager<'a> {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr, std::marker::PhantomData)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}

impl<'a> FfiHandle for MmioDeviceManager<'a> {
    const C_HANDLE_NAME: &'static str = "MmioDeviceManager";
    const TYPE_TAG: u32 = 16777218u32;
    unsafe fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
    fn __from_raw(handle: *mut core::ffi::c_void) -> Self {
        Self(handle, std::marker::PhantomData)
    }
}

impl<'a> FfiType for MmioDeviceManager<'a> {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "MmioDeviceManager";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    unsafe fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}

impl<'a> std::fmt::Debug for MmioDeviceManager<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("MmioDeviceManager").field(&self.0).finish()
    }
}

impl<'a> MmioDeviceManager<'a> {
    #[doc = " Create an empty device manager."]
    pub fn new() -> MmioDeviceManager<'a> {
        let __raw = unsafe { krun_mmio_device_manager_new() };
        unsafe { <MmioDeviceManager<'a> as FfiType>::from_c(__raw) }
    }
    #[doc = " Add a device to this manager."]
    #[doc = ""]
    #[doc = " Devices are attached in the order they are added. The device must"]
    #[doc = " implement [`AttachDevice`] — all built-in device types"]
    #[doc = " (`FsDevice`, `ConsoleDevice`, etc.) implement this trait."]
    pub fn add(&mut self, device: impl AttachDevice<'a>) -> &mut Self {
        unsafe { krun_mmio_device_manager_add(self.0, device.__into_raw_handle()) };
        self
    }
}

impl<'a> Drop for MmioDeviceManager<'a> {
    fn drop(&mut self) {
        unsafe { krun_mmio_device_manager_destroy(self.0) }
    }
}

unsafe extern "C" {
    pub fn krun_fs_device_destroy(handle: *mut core::ffi::c_void);
    pub fn krun_fs_device_new(
        tag: <&'static str as FfiType>::CRepr,
        host_path: <&'static str as FfiType>::CRepr,
        err_out: *mut *mut core::ffi::c_void,
    ) -> *mut core::ffi::c_void;
    pub fn krun_fs_device_new_read_only(
        tag: <&'static str as FfiType>::CRepr,
        host_path: <&'static str as FfiType>::CRepr,
        err_out: *mut *mut core::ffi::c_void,
    ) -> *mut core::ffi::c_void;
    pub fn krun_fs_device_new_null(
        tag: <&'static str as FfiType>::CRepr,
        err_out: *mut *mut core::ffi::c_void,
    ) -> *mut core::ffi::c_void;
}

pub struct FsDevice<'a>(*mut core::ffi::c_void, std::marker::PhantomData<&'a ()>);

impl<'a> FsDevice<'a> {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr, std::marker::PhantomData)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}

impl<'a> FfiHandle for FsDevice<'a> {
    const C_HANDLE_NAME: &'static str = "FsDevice";
    const TYPE_TAG: u32 = 16777219u32;
    unsafe fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
    fn __from_raw(handle: *mut core::ffi::c_void) -> Self {
        Self(handle, std::marker::PhantomData)
    }
}

impl<'a> FfiType for FsDevice<'a> {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "FsDevice";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    unsafe fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}

impl<'a> std::fmt::Debug for FsDevice<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("FsDevice").field(&self.0).finish()
    }
}

impl<'a> FsDevice<'a> {
    #[doc = " Create a new virtiofs device sharing a host directory."]
    #[doc = ""]
    #[doc = " # Arguments"]
    #[doc = ""]
    #[doc = " - `tag`: the filesystem tag visible to the guest (e.g. `\"/dev/root\"`)."]
    #[doc = " - `host_path`: the host directory to share."]
    pub fn new(tag: &str, host_path: &str) -> Result<FsDevice<'a>, Error> {
        let mut __err: *mut core::ffi::c_void = core::ptr::null_mut();
        let __raw = unsafe {
            krun_fs_device_new(
                <&str as FfiType>::into_c(tag),
                <&str as FfiType>::into_c(host_path),
                &mut __err as *mut *mut core::ffi::c_void,
            )
        };
        if !__raw.is_null() {
            Ok(unsafe { <FsDevice<'a> as FfiType>::from_c(__raw) })
        } else {
            let __r = unsafe { krun_error_result(__err) };
            Err(Error::from_ffi(__r, __err))
        }
    }
    #[doc = " Create a read-only virtiofs device sharing a host directory."]
    pub fn new_read_only(tag: &str, host_path: &str) -> Result<FsDevice<'a>, Error> {
        let mut __err: *mut core::ffi::c_void = core::ptr::null_mut();
        let __raw = unsafe {
            krun_fs_device_new_read_only(
                <&str as FfiType>::into_c(tag),
                <&str as FfiType>::into_c(host_path),
                &mut __err as *mut *mut core::ffi::c_void,
            )
        };
        if !__raw.is_null() {
            Ok(unsafe { <FsDevice<'a> as FfiType>::from_c(__raw) })
        } else {
            let __r = unsafe { krun_error_result(__err) };
            Err(Error::from_ffi(__r, __err))
        }
    }
    #[doc = " Create a virtiofs device with no host directory (NullFs)."]
    #[doc = ""]
    #[doc = " The guest sees an empty filesystem. Use [`inject`](Self::inject)"]
    #[doc = " and [`add_overlay_dir`](Self::add_overlay_dir) to populate it"]
    #[doc = " with virtual entries."]
    pub fn new_null(tag: &str) -> Result<FsDevice<'a>, Error> {
        let mut __err: *mut core::ffi::c_void = core::ptr::null_mut();
        let __raw = unsafe {
            krun_fs_device_new_null(
                <&str as FfiType>::into_c(tag),
                &mut __err as *mut *mut core::ffi::c_void,
            )
        };
        if !__raw.is_null() {
            Ok(unsafe { <FsDevice<'a> as FfiType>::from_c(__raw) })
        } else {
            let __r = unsafe { krun_error_result(__err) };
            Err(Error::from_ffi(__r, __err))
        }
    }
}

impl<'a> Drop for FsDevice<'a> {
    fn drop(&mut self) {
        unsafe { krun_fs_device_destroy(self.0) }
    }
}

unsafe extern "C" {
    pub fn krun_console_device_destroy(handle: *mut core::ffi::c_void);
    pub fn krun_console_device_builder() -> <ConsoleBuilder<'static> as FfiType>::CRepr;
}

pub struct ConsoleDevice<'a>(*mut core::ffi::c_void, std::marker::PhantomData<&'a ()>);

impl<'a> ConsoleDevice<'a> {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr, std::marker::PhantomData)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}

impl<'a> FfiHandle for ConsoleDevice<'a> {
    const C_HANDLE_NAME: &'static str = "ConsoleDevice";
    const TYPE_TAG: u32 = 16777220u32;
    unsafe fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
    fn __from_raw(handle: *mut core::ffi::c_void) -> Self {
        Self(handle, std::marker::PhantomData)
    }
}

impl<'a> FfiType for ConsoleDevice<'a> {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "ConsoleDevice";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    unsafe fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}

impl<'a> std::fmt::Debug for ConsoleDevice<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("ConsoleDevice").field(&self.0).finish()
    }
}

impl<'a> ConsoleDevice<'a> {
    #[doc = " Create a new console builder."]
    pub fn builder() -> ConsoleBuilder<'a> {
        let __raw = unsafe { krun_console_device_builder() };
        unsafe { <ConsoleBuilder<'a> as FfiType>::from_c(__raw) }
    }
}

impl<'a> Drop for ConsoleDevice<'a> {
    fn drop(&mut self) {
        unsafe { krun_console_device_destroy(self.0) }
    }
}

unsafe extern "C" {
    pub fn krun_console_builder_destroy(handle: *mut core::ffi::c_void);
    pub fn krun_console_builder_add_tty_port(
        handle: *mut core::ffi::c_void,
        name: <&'static str as FfiType>::CRepr,
        tty_fd: <BorrowedFd<'static> as FfiType>::CRepr,
        result: *mut <u32 as FfiType>::CRepr,
        err_out: *mut *mut core::ffi::c_void,
    ) -> ffier::FfierResult;
    pub fn krun_console_builder_set_kernel_console(
        handle: *mut core::ffi::c_void,
        port_index: <u32 as FfiType>::CRepr,
        err_out: *mut *mut core::ffi::c_void,
    ) -> ffier::FfierResult;
    pub fn krun_console_builder_build(
        handle: *mut core::ffi::c_void,
        err_out: *mut *mut core::ffi::c_void,
    ) -> *mut core::ffi::c_void;
    pub fn krun_console_builder_add_default_console(
        handle: *mut core::ffi::c_void,
        stdin: <Option<BorrowedFd<'static>> as FfiType>::CRepr,
        stdout: <Option<BorrowedFd<'static>> as FfiType>::CRepr,
        stderr: <Option<BorrowedFd<'static>> as FfiType>::CRepr,
        err_out: *mut *mut core::ffi::c_void,
    ) -> ffier::FfierResult;
}

pub struct ConsoleBuilder<'a>(*mut core::ffi::c_void, std::marker::PhantomData<&'a ()>);

impl<'a> ConsoleBuilder<'a> {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr, std::marker::PhantomData)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}

impl<'a> FfiHandle for ConsoleBuilder<'a> {
    const C_HANDLE_NAME: &'static str = "ConsoleBuilder";
    const TYPE_TAG: u32 = 16777221u32;
    unsafe fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
    fn __from_raw(handle: *mut core::ffi::c_void) -> Self {
        Self(handle, std::marker::PhantomData)
    }
}

impl<'a> FfiType for ConsoleBuilder<'a> {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "ConsoleBuilder";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    unsafe fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}

impl<'a> std::fmt::Debug for ConsoleBuilder<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("ConsoleBuilder").field(&self.0).finish()
    }
}

impl<'a> ConsoleBuilder<'a> {
    #[doc = " Add a TTY-backed port to the console."]
    #[doc = ""]
    #[doc = " If the fd refers to a real terminal, raw mode will be enabled on it"]
    #[doc = " when the VM starts, and restored on shutdown."]
    #[doc = ""]
    #[doc = " # Arguments"]
    #[doc = ""]
    #[doc = " - `name`: the port name visible to the guest (e.g. `\"tty0\"`)."]
    #[doc = " - `tty_fd`: borrowed fd for the host TTY; duplicated internally, caller retains ownership."]
    #[doc = ""]
    #[doc = " # Returns"]
    #[doc = ""]
    #[doc = " The zero-based port index, usable with [`set_kernel_console`](ConsoleBuilder::set_kernel_console)."]
    pub fn add_tty_port(&mut self, name: &str, tty_fd: BorrowedFd<'a>) -> Result<u32, Error> {
        let mut __out = std::mem::MaybeUninit::uninit();
        let mut __err: *mut core::ffi::c_void = core::ptr::null_mut();
        let __r = unsafe {
            krun_console_builder_add_tty_port(
                self.0,
                <&str as FfiType>::into_c(name),
                <BorrowedFd<'a> as FfiType>::into_c(tty_fd),
                __out.as_mut_ptr(),
                &mut __err as *mut *mut core::ffi::c_void,
            )
        };
        if __r == 0 {
            Ok(unsafe { <u32 as FfiType>::from_c(__out.assume_init()) })
        } else {
            Err(Error::from_ffi(__r, __err))
        }
    }
    #[doc = " Designate a port as the kernel console (`console=hvcN`)."]
    #[doc = ""]
    #[doc = " # Arguments"]
    #[doc = ""]
    #[doc = " - `port_index`: a value returned by [`add_tty_port`](ConsoleBuilder::add_tty_port)."]
    pub fn set_kernel_console(&mut self, port_index: u32) -> Result<(), Error> {
        let mut __err: *mut core::ffi::c_void = core::ptr::null_mut();
        let __r = unsafe {
            krun_console_builder_set_kernel_console(
                self.0,
                <u32 as FfiType>::into_c(port_index),
                &mut __err as *mut *mut core::ffi::c_void,
            )
        };
        if __r == 0 {
            Ok(())
        } else {
            Err(Error::from_ffi(__r, __err))
        }
    }
    #[doc = " Build the console device. At least one port must have been added."]
    pub fn build(self) -> Result<ConsoleDevice<'a>, Error> {
        let __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        let mut __err: *mut core::ffi::c_void = core::ptr::null_mut();
        let __raw = unsafe {
            krun_console_builder_build(__handle, &mut __err as *mut *mut core::ffi::c_void)
        };
        if !__raw.is_null() {
            Ok(unsafe { <ConsoleDevice<'a> as FfiType>::from_c(__raw) })
        } else {
            let __r = unsafe { krun_error_result(__err) };
            Err(Error::from_ffi(__r, __err))
        }
    }
    #[doc = " Set up the default console: port 0 (hvc0) plus named redirect ports."]
    #[doc = ""]
    #[doc = " Replicates the v1 `krun_add_virtio_console_default` behaviour:"]
    #[doc = ""]
    #[doc = " - If any fd is a terminal, port 0 becomes a full TTY console"]
    #[doc = "   (raw mode enabled), and that fd is NOT added as a redirect port."]
    #[doc = " - Otherwise, port 0 gets log output and named redirect ports"]
    #[doc = "   (`krun-stdin`, `krun-stdout`, `krun-stderr`) are added."]
    #[doc = ""]
    #[doc = " Pass `None` to skip a stream."]
    pub fn add_default_console(
        &mut self,
        stdin: Option<BorrowedFd<'a>>,
        stdout: Option<BorrowedFd<'a>>,
        stderr: Option<BorrowedFd<'a>>,
    ) -> Result<(), Error> {
        let mut __err: *mut core::ffi::c_void = core::ptr::null_mut();
        let __r = unsafe {
            krun_console_builder_add_default_console(
                self.0,
                <Option<BorrowedFd<'a>> as FfiType>::into_c(stdin),
                <Option<BorrowedFd<'a>> as FfiType>::into_c(stdout),
                <Option<BorrowedFd<'a>> as FfiType>::into_c(stderr),
                &mut __err as *mut *mut core::ffi::c_void,
            )
        };
        if __r == 0 {
            Ok(())
        } else {
            Err(Error::from_ffi(__r, __err))
        }
    }
}

impl<'a> Drop for ConsoleBuilder<'a> {
    fn drop(&mut self) {
        unsafe { krun_console_builder_destroy(self.0) }
    }
}

unsafe extern "C" {
    pub fn krun_balloon_device_destroy(handle: *mut core::ffi::c_void);
    pub fn krun_balloon_device_new(err_out: *mut *mut core::ffi::c_void) -> *mut core::ffi::c_void;
}

pub struct BalloonDevice(*mut core::ffi::c_void);

impl BalloonDevice {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}

impl FfiHandle for BalloonDevice {
    const C_HANDLE_NAME: &'static str = "BalloonDevice";
    const TYPE_TAG: u32 = 16777222u32;
    unsafe fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
    fn __from_raw(handle: *mut core::ffi::c_void) -> Self {
        Self(handle)
    }
}

impl FfiType for BalloonDevice {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "BalloonDevice";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    unsafe fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}

impl std::fmt::Debug for BalloonDevice {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("BalloonDevice").field(&self.0).finish()
    }
}

impl BalloonDevice {
    #[doc = " Create a new balloon device."]
    pub fn new() -> Result<BalloonDevice, Error> {
        let mut __err: *mut core::ffi::c_void = core::ptr::null_mut();
        let __raw = unsafe { krun_balloon_device_new(&mut __err as *mut *mut core::ffi::c_void) };
        if !__raw.is_null() {
            Ok(unsafe { <BalloonDevice as FfiType>::from_c(__raw) })
        } else {
            let __r = unsafe { krun_error_result(__err) };
            Err(Error::from_ffi(__r, __err))
        }
    }
}

impl Drop for BalloonDevice {
    fn drop(&mut self) {
        unsafe { krun_balloon_device_destroy(self.0) }
    }
}

unsafe extern "C" {
    pub fn krun_rng_device_destroy(handle: *mut core::ffi::c_void);
    pub fn krun_rng_device_new(err_out: *mut *mut core::ffi::c_void) -> *mut core::ffi::c_void;
}

pub struct RngDevice(*mut core::ffi::c_void);

impl RngDevice {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}

impl FfiHandle for RngDevice {
    const C_HANDLE_NAME: &'static str = "RngDevice";
    const TYPE_TAG: u32 = 16777223u32;
    unsafe fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
    fn __from_raw(handle: *mut core::ffi::c_void) -> Self {
        Self(handle)
    }
}

impl FfiType for RngDevice {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "RngDevice";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    unsafe fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}

impl std::fmt::Debug for RngDevice {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("RngDevice").field(&self.0).finish()
    }
}

impl RngDevice {
    #[doc = " Create a new RNG device."]
    pub fn new() -> Result<RngDevice, Error> {
        let mut __err: *mut core::ffi::c_void = core::ptr::null_mut();
        let __raw = unsafe { krun_rng_device_new(&mut __err as *mut *mut core::ffi::c_void) };
        if !__raw.is_null() {
            Ok(unsafe { <RngDevice as FfiType>::from_c(__raw) })
        } else {
            let __r = unsafe { krun_error_result(__err) };
            Err(Error::from_ffi(__r, __err))
        }
    }
}

impl Drop for RngDevice {
    fn drop(&mut self) {
        unsafe { krun_rng_device_destroy(self.0) }
    }
}

unsafe extern "C" {
    pub fn krun_krunfw_destroy(handle: *mut core::ffi::c_void);
    pub fn krun_krunfw_load() -> <Krunfw as FfiType>::CRepr;
}

pub struct Krunfw(*mut core::ffi::c_void);

impl Krunfw {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}

impl FfiHandle for Krunfw {
    const C_HANDLE_NAME: &'static str = "Krunfw";
    const TYPE_TAG: u32 = 16777224u32;
    unsafe fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
    fn __from_raw(handle: *mut core::ffi::c_void) -> Self {
        Self(handle)
    }
}

impl FfiType for Krunfw {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Krunfw";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    unsafe fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}

impl std::fmt::Debug for Krunfw {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Krunfw").field(&self.0).finish()
    }
}

impl Krunfw {
    #[doc = " Load the krunfw kernel payload."]
    pub fn load() -> Krunfw {
        let __raw = unsafe { krun_krunfw_load() };
        unsafe { <Krunfw as FfiType>::from_c(__raw) }
    }
}

impl Drop for Krunfw {
    fn drop(&mut self) {
        unsafe { krun_krunfw_destroy(self.0) }
    }
}

unsafe extern "C" {
    pub fn krun_vmm_builder_destroy(handle: *mut core::ffi::c_void);
    pub fn krun_vmm_builder_new() -> <VmmBuilder<'static> as FfiType>::CRepr;
    pub fn krun_vmm_builder_vcpus(
        handle: *mut core::ffi::c_void,
        count: <u8 as FfiType>::CRepr,
        err_out: *mut *mut core::ffi::c_void,
    ) -> ffier::FfierResult;
    pub fn krun_vmm_builder_ram_mib(
        handle: *mut core::ffi::c_void,
        mib: <u32 as FfiType>::CRepr,
        err_out: *mut *mut core::ffi::c_void,
    ) -> ffier::FfierResult;
    pub fn krun_vmm_builder_payload(
        handle: *mut core::ffi::c_void,
        payload: *mut core::ffi::c_void,
    );
    pub fn krun_vmm_builder_devices(
        handle: *mut core::ffi::c_void,
        devices: <MmioDeviceManager<'static> as FfiType>::CRepr,
    );
    pub fn krun_vmm_builder_build(
        handle: *mut core::ffi::c_void,
        err_out: *mut *mut core::ffi::c_void,
    ) -> *mut core::ffi::c_void;
}

pub struct VmmBuilder<'a>(*mut core::ffi::c_void, std::marker::PhantomData<&'a ()>);

impl<'a> VmmBuilder<'a> {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr, std::marker::PhantomData)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}

impl<'a> FfiHandle for VmmBuilder<'a> {
    const C_HANDLE_NAME: &'static str = "VmmBuilder";
    const TYPE_TAG: u32 = 16777226u32;
    unsafe fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
    fn __from_raw(handle: *mut core::ffi::c_void) -> Self {
        Self(handle, std::marker::PhantomData)
    }
}

impl<'a> FfiType for VmmBuilder<'a> {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "VmmBuilder";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    unsafe fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}

impl<'a> std::fmt::Debug for VmmBuilder<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("VmmBuilder").field(&self.0).finish()
    }
}

impl<'a> VmmBuilder<'a> {
    #[doc = " Create a new VM builder with no configuration."]
    pub fn new() -> VmmBuilder<'a> {
        let __raw = unsafe { krun_vmm_builder_new() };
        unsafe { <VmmBuilder<'a> as FfiType>::from_c(__raw) }
    }
    #[doc = " Set the number of virtual CPUs. Must be at least 1."]
    pub fn vcpus(self, count: u8) -> Result<Self, Error> {
        let mut __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        let mut __err: *mut core::ffi::c_void = core::ptr::null_mut();
        let __r = unsafe {
            krun_vmm_builder_vcpus(
                &mut __handle as *mut *mut core::ffi::c_void as *mut core::ffi::c_void,
                <u8 as FfiType>::into_c(count),
                &mut __err as *mut *mut core::ffi::c_void,
            )
        };
        if __r == 0 {
            Ok(Self(__handle, std::marker::PhantomData))
        } else {
            Err(Error::from_ffi(__r, __err))
        }
    }
    #[doc = " Set the amount of guest RAM in mebibytes. Must be at least 1."]
    pub fn ram_mib(self, mib: u32) -> Result<Self, Error> {
        let mut __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        let mut __err: *mut core::ffi::c_void = core::ptr::null_mut();
        let __r = unsafe {
            krun_vmm_builder_ram_mib(
                &mut __handle as *mut *mut core::ffi::c_void as *mut core::ffi::c_void,
                <u32 as FfiType>::into_c(mib),
                &mut __err as *mut *mut core::ffi::c_void,
            )
        };
        if __r == 0 {
            Ok(Self(__handle, std::marker::PhantomData))
        } else {
            Err(Error::from_ffi(__r, __err))
        }
    }
    #[doc = " Set the payload to run inside the VM."]
    #[doc = ""]
    #[doc = " Currently the only payload type is `Init`, which runs a process"]
    #[doc = " as PID 1 inside the guest using the built-in krun init."]
    pub fn payload(self, payload: impl Payload) -> Self {
        let mut __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        unsafe {
            krun_vmm_builder_payload(
                &mut __handle as *mut *mut core::ffi::c_void as *mut core::ffi::c_void,
                payload.__into_raw_handle(),
            )
        };
        Self(__handle, std::marker::PhantomData)
    }
    #[doc = " Set the device manager containing all virtio devices."]
    #[doc = ""]
    #[doc = " The device manager determines which transport bus is used (currently"]
    #[doc = " only [`MmioDeviceManager`] for virtio-mmio)."]
    pub fn devices(self, devices: MmioDeviceManager<'a>) -> Self {
        let mut __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        unsafe {
            krun_vmm_builder_devices(
                &mut __handle as *mut *mut core::ffi::c_void as *mut core::ffi::c_void,
                <MmioDeviceManager<'a> as FfiType>::into_c(devices),
            )
        };
        Self(__handle, std::marker::PhantomData)
    }
    #[doc = " Build the VM, creating guest memory, attaching devices, and starting"]
    #[doc = " vCPUs. All required fields (`vcpus`, `ram_mib`, `payload`, `devices`)"]
    #[doc = " must have been set."]
    pub fn build(self) -> Result<Vmm<'a>, Error> {
        let mut __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        let mut __err: *mut core::ffi::c_void = core::ptr::null_mut();
        let __raw = unsafe {
            krun_vmm_builder_build(
                &mut __handle as *mut *mut core::ffi::c_void as *mut core::ffi::c_void,
                &mut __err as *mut *mut core::ffi::c_void,
            )
        };
        if !__raw.is_null() {
            Ok(unsafe { <Vmm<'a> as FfiType>::from_c(__raw) })
        } else {
            let __r = unsafe { krun_error_result(__err) };
            Err(Error::from_ffi(__r, __err))
        }
    }
}

impl<'a> Drop for VmmBuilder<'a> {
    fn drop(&mut self) {
        unsafe { krun_vmm_builder_destroy(self.0) }
    }
}

unsafe extern "C" {
    pub fn krun_vmm_destroy(handle: *mut core::ffi::c_void);
    pub fn krun_vmm_run(handle: *mut core::ffi::c_void);
}

pub struct Vmm<'a>(*mut core::ffi::c_void, std::marker::PhantomData<&'a ()>);

impl<'a> Vmm<'a> {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr, std::marker::PhantomData)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}

impl<'a> FfiHandle for Vmm<'a> {
    const C_HANDLE_NAME: &'static str = "Vmm";
    const TYPE_TAG: u32 = 16777227u32;
    unsafe fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
    fn __from_raw(handle: *mut core::ffi::c_void) -> Self {
        Self(handle, std::marker::PhantomData)
    }
}

impl<'a> FfiType for Vmm<'a> {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Vmm";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    unsafe fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}

impl<'a> std::fmt::Debug for Vmm<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Vmm").field(&self.0).finish()
    }
}

impl<'a> Vmm<'a> {
    #[doc = " Run the VM event loop. This call blocks until the VM exits or a"]
    #[doc = " fatal error occurs."]
    pub fn run(&mut self) {
        unsafe { krun_vmm_run(self.0) }
    }
}

impl<'a> Drop for Vmm<'a> {
    fn drop(&mut self) {
        unsafe { krun_vmm_destroy(self.0) }
    }
}

pub trait PushStr {
    fn push(&mut self, s: &str) -> bool;
    #[doc(hidden)]
    fn __ffier_vtable() -> &'static PushStrVtable
    where
        Self: Sized,
    {
        &PushStrVtable {
            drop: Some({
                unsafe extern "C" fn __drop_trampoline<__T>(__ud: *mut core::ffi::c_void) {
                    unsafe { drop(Box::from_raw(__ud as *mut __T)) };
                }
                __drop_trampoline::<Self>
            }),
            push: Some({
                unsafe extern "C" fn __trampoline<__T: PushStr>(
                    __ud: *mut core::ffi::c_void,
                    s: <&'static str as FfiType>::CRepr,
                ) -> <bool as FfiType>::CRepr {
                    let __val = unsafe { &mut *(__ud as *mut __T) };
                    let __result = __val.push(unsafe { <&str as FfiType>::from_c(s) });
                    <bool as FfiType>::into_c(__result)
                }
                __trampoline::<Self>
            }),
        }
    }
    #[doc(hidden)]
    fn __into_raw_handle(self) -> *mut core::ffi::c_void
    where
        Self: Sized,
    {
        let __vtable: &'static PushStrVtable = Self::__ffier_vtable();
        let __user_data = Box::into_raw(Box::new(self));
        let vtable_size: u16 = core::mem::size_of::<PushStrVtable>()
            .try_into()
            .expect("vtable_size exceeds u16::MAX");
        ffier::ffier_handle_new_with_metadata(
            16777228u32,
            0,
            ffier::VtableHandle {
                vtable_ptr: __vtable as *const PushStrVtable as *const core::ffi::c_void,
                user_data: __user_data as *const core::ffi::c_void,
                vtable_size,
            },
        )
    }
}

#[repr(C)]
pub struct PushStrVtable {
    pub drop: Option<unsafe extern "C" fn(*mut core::ffi::c_void)>,
    pub push: Option<
        unsafe extern "C" fn(
            *mut core::ffi::c_void,
            <&'static str as FfiType>::CRepr,
        ) -> <bool as FfiType>::CRepr,
    >,
}

pub struct VtablePushStr(*mut core::ffi::c_void);

impl VtablePushStr {
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}

impl Drop for VtablePushStr {
    fn drop(&mut self) {}
}

unsafe extern "C" {
    pub fn krun_error_code(handle: *mut core::ffi::c_void) -> <u32 as FfiType>::CRepr;
    pub fn krun_error_message(handle: *mut core::ffi::c_void, writer: *mut core::ffi::c_void);
    pub fn krun_error_result(handle: *mut core::ffi::c_void) -> <u64 as FfiType>::CRepr;
    pub fn krun_error_destroy(handle: *mut core::ffi::c_void);
}

pub trait Payload {
    #[doc(hidden)]
    fn __into_raw_handle(self) -> *mut core::ffi::c_void
    where
        Self: Sized;
}

impl Payload for Krunfw {
    fn __into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}

pub trait AttachDevice<'a> {
    #[doc(hidden)]
    fn __into_raw_handle(self) -> *mut core::ffi::c_void
    where
        Self: Sized;
}

impl<'a> AttachDevice<'a> for FsDevice<'a> {
    fn __into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}

impl<'a> AttachDevice<'a> for ConsoleDevice<'a> {
    fn __into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}

impl<'a> AttachDevice<'a> for BalloonDevice {
    fn __into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}

impl<'a> AttachDevice<'a> for RngDevice {
    fn __into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}

unsafe extern "C" {
    pub fn krun_init_log(
        target: <LogTarget as FfiType>::CRepr,
        level: <LogLevel as FfiType>::CRepr,
        style: <LogStyle as FfiType>::CRepr,
        err_out: *mut *mut core::ffi::c_void,
    ) -> ffier::FfierResult;
}

pub fn init_log(target: LogTarget, level: LogLevel, style: LogStyle) -> Result<(), Error> {
    let mut __err: *mut core::ffi::c_void = core::ptr::null_mut();
    let __r = unsafe {
        krun_init_log(
            <LogTarget as FfiType>::into_c(target),
            <LogLevel as FfiType>::into_c(level),
            <LogStyle as FfiType>::into_c(style),
            &mut __err as *mut *mut core::ffi::c_void,
        )
    };
    if __r == 0 {
        Ok(())
    } else {
        Err(Error::from_ffi(__r, __err))
    }
}
