name: macOS-aarch64
on: [pull_request, create]

jobs:
  build:
    if: github.event_name == 'pull_request'
    name: Code Quality (fmt, clippy)
    runs-on: macos-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt, clippy

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install dependencies
        run: brew tap slp/krunkit && brew install virglrenderer clang-format

      - name: Formatting (clang-format)
        run: find init -iname '*.h' -o -iname '*.c' | xargs clang-format -n -Werror

      - name: Formatting (rustfmt)
        run: cargo fmt -- --check

      - name: Formatting (rustfmt)
        run: cargo clippy --features efi,gpu -- -D warnings
