name: Code Formatting
on: [pull_request]

jobs:
  formatting:
    name: clang-format + cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup build environment
        uses: ./.github/actions/setup-build-env
      
      - name: C code formatting
        run: find init -iname '*.h' -o -iname '*.c' | xargs clang-format -n -Werror
      
      - name: Rust code formatting
        run: cargo fmt -- --check
      
      - name: Rust code formatting (examples)
        run: cd examples; cargo fmt -- --check
      
      - name: Rust code formatting (tests)
        run: cd tests; cargo fmt -- --check
